env:
  browser: true
  es6: true
  jest/globals: true
  cypress/globals: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jest
  - cypress
rules: {}
